language: cpp
compiler: gcc

os: linux
dist: focal

addons:
  apt:
    packages:
      - gcc-10
      - cmake
      - qtbase5-dev
      - qtbase5-dev-tools
      - qt5-default
      - libcuda-10.2
      - libopencv-dev
      - libarrayfire-unified-dev
      - libboost-all-dev
      - doctest-dev

script:
  ./build.sh

branches:
  only:
    - dev
    - /^feature*$\
    - /^refactor*$\
    - /^fix*$\

notifications:
  email: false